[project]
name = "intel-cicd-repo-infrastructure"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
  "pytest",
  "pytest-xdist",
  "hypothesis",
  "black",
  "mypy",
  "cmakelang",
  "pyyaml",
  "clang-format",
  "ruff"
]
license = "BSL-1.0"

[project.urls]
Repository = "https://github.com/intel/cicd-repo-infrastructure/"
Documentation = "https://intel.github.io/cicd-repo-infrastructure/"

[tool.setuptools]
packages = []
