name: Usage Test
permissions: read-all

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'cmake-**'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'cmake-**'

env:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_GENERATOR: Ninja
  TARGET_LLVM_VERSION: 21
  MULL_LLVM_MAJOR_VERSION: 19
  MULL_LLVM_VERSION: 19.1.1
  MULL_VERSION: 0.27.1

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-' || '' }}ubuntu-24.04
    steps:
      - name: Set up python venv
        run: |
          python3 -m venv ${{github.workspace}}/test_venv
          source ${{github.workspace}}/test_venv/bin/activate
          echo "${{github.workspace}}/test_venv/bin" >> $GITHUB_PATH
          echo $VIRTUAL_ENV

      - name: Check venv
        run: |
          echo $VIRTUAL_ENV
