name: Usage Test
permissions: read-all

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'cmake-**'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'cmake-**'

env:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_GENERATOR: Ninja
  TARGET_LLVM_VERSION: 22
  MULL_LLVM_MAJOR_VERSION: 20
  MULL_LLVM_VERSION: 20.1.2
  MULL_VERSION: 0.34.0

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: &runner ${{ github.repository_owner == 'intel' && 'intel-' || '' }}ubuntu-24.04
    steps:
      - &add-llvm-repo
        name: Add LLVM repository
        run: |
          DISTRO="$(lsb_release -cs)"
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo add-apt-repository -y deb "https://apt.llvm.org/$DISTRO/" "llvm-toolchain-$DISTRO-${{env.TARGET_LLVM_VERSION}}" main
          sudo apt update

      - name: Install build tools
        run: sudo apt install -y pip ninja-build clang-${{env.TARGET_LLVM_VERSION}} clang-tidy-${{env.TARGET_LLVM_VERSION}} clang-format-${{env.TARGET_LLVM_VERSION}}

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 20

      - name: Install Mermaid
        run: |
          npm install -g @mermaid-js/mermaid-cli@11.4.2
          npx puppeteer browsers install chrome-headless-shell

      - name: Install asciidoctor
        run: |
          sudo apt install -y asciidoctor
          sudo gem install asciidoctor asciidoctor-diagram rouge

      - name: Checkout target branch
        uses: &checkout actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{github.base_ref}}

      - name: Extract target branch SHA
        run: echo "branch=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
        id: target_branch

      - name: Checkout PR branch
        uses: *checkout

      - name: Install python test requirements
        run: |
          python3 -m venv "${{github.workspace}}/test_venv"
          source "${{github.workspace}}/test_venv/bin/activate"
          pip install -r "${{github.workspace}}/requirements.txt"
          echo "${{github.workspace}}/test_venv/bin" >> "$GITHUB_PATH"

      - name: Install cmake-format
        run: |
          pip install cmakelang pyyaml

      - name: Install python quality tools
        run: |
          pip install mypy black

      - name: Configure cmake for lib
        env:
          CC: "/usr/lib/llvm-${{env.TARGET_LLVM_VERSION}}/bin/clang"
          CXX: "/usr/lib/llvm-${{env.TARGET_LLVM_VERSION}}/bin/clang++"
          PR_TARGET_BRANCH: ${{ steps.target_branch.outputs.branch }}
        working-directory: ${{github.workspace}}/test/library
        run: cmake -Bbuild -DCPM_SOURCE_CACHE=~/cpm-cache -DINFRA_TARGET_NAMESPACE=infra

      - name: Build lib docs
        working-directory: ${{github.workspace}}/test/library
        run: test "$(cmake --build build -v -t infra.docs | grep -c ERROR)" == 0

      - name: Build lib metabench tests
        working-directory: ${{github.workspace}}/test/library
        run: cmake --build build -t infra.metabench_tests

      - name: Check lib quality
        working-directory: ${{github.workspace}}/test/library
        run: cmake --build build -t infra.ci-quality

      - &restore_cpm_cache
        name: Restore CPM cache
        env:
          cache-name: cpm-cache-0
        id: cpm-cache-restore
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/cpm-cache
          key: ${{runner.os}}-${{env.cache-name}}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**') }}
          restore-keys: |
            ${{runner.os}}-${{env.cache-name}}-

      - name: Configure cmake for app
        env:
          CC: "/usr/lib/llvm-${{env.TARGET_LLVM_VERSION}}/bin/clang"
          CXX: "/usr/lib/llvm-${{env.TARGET_LLVM_VERSION}}/bin/clang++"
          PR_TARGET_BRANCH: ${{ steps.target_branch.outputs.branch }}
        working-directory: ${{github.workspace}}/test/application
        run: cmake -Bbuild -DCPM_SOURCE_CACHE=~/cpm-cache -DINFRA_TARGET_NAMESPACE=infra

      - &save_cpm_cache
        name: Save CPM cache
        env:
          cache-name: cpm-cache-0
        if: steps.cpm-cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/cpm-cache
          key: ${{runner.os}}-${{env.cache-name}}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**') }}

      - name: Build app and run tests
        working-directory: ${{github.workspace}}/test/application
        run: |
          cmake --build build -t infra.build_unit_tests
          ctest --output-on-failure --test-dir build

      - name: Run benchmarks
        working-directory: ${{github.workspace}}/test/application
        run: |
          cmake --build build -t infra.benchmarks

      - name: Run recipe tests
        working-directory: ${{github.workspace}}/test/application
        run: |
          cmake --build build -t recipe_tests

      - name: Generate coverage report
        working-directory: ${{github.workspace}}/test/application
        run: |
          cmake --build build -t infra.cpp_coverage_report
          { echo "<details>";
          echo "<summary>Coverage report:</summary>";
          cat ./build/coverage_report.txt;
          echo "</details>"; } >> "$GITHUB_STEP_SUMMARY"

      - name: Check app quality
        working-directory: ${{github.workspace}}/test/application
        run: cmake --build build -t infra.ci-quality

      - name: Verify app setup
        working-directory: ${{github.workspace}}/test
        run: ./verify_links.sh

  sanitize:
    runs-on: *runner
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [undefined, address]

    steps:
      - name: Checkout PR branch
        uses: *checkout

      - *add-llvm-repo

      - name: Install build tools
        run: sudo apt install -y ninja-build clang-${{env.TARGET_LLVM_VERSION}} clang-tidy-${{env.TARGET_LLVM_VERSION}} clang-format-${{env.TARGET_LLVM_VERSION}}

      - *restore_cpm_cache

      - name: Configure cmake for app
        env:
          CC: "/usr/lib/llvm-${{env.TARGET_LLVM_VERSION}}/bin/clang"
          CXX: "/usr/lib/llvm-${{env.TARGET_LLVM_VERSION}}/bin/clang++"
          SANITIZERS: ${{matrix.sanitizer}}
        working-directory: ${{github.workspace}}/test/application
        run: cmake -Bbuild -DCPM_SOURCE_CACHE=~/cpm-cache -DINFRA_TARGET_NAMESPACE=infra

      - *save_cpm_cache

      # https://github.com/actions/runner-images/issues/9524
      - name: Fix kernel mmap rnd bits
        # Asan in llvm 14 provided in ubuntu 22.04 is incompatible with
        # high-entropy ASLR in much newer kernels that GitHub runners are
        # using leading to random crashes: https://reviews.llvm.org/D148280
        run: sudo sysctl vm.mmap_rnd_bits=28

      - name: Build app and run tests
        working-directory: ${{github.workspace}}/test/application
        run: cmake --build build -t infra.cpp_tests

  mutate:
    runs-on: *runner
    steps:
      - name: Checkout PR branch
        uses: *checkout

      - *add-llvm-repo

      - name: Install build tools
        run: sudo apt install -y ninja-build clang-${{env.MULL_LLVM_MAJOR_VERSION}}

      - name: Install mull
        env:
          mull-pkg: Mull-${{env.MULL_LLVM_MAJOR_VERSION}}-${{env.MULL_VERSION}}-LLVM-${{env.MULL_LLVM_VERSION}}-ubuntu-amd64-24.04.deb
        run: |
          MULL_DEB="$(mktemp)"
          wget -O "$MULL_DEB" https://github.com/mull-project/mull/releases/download/${{env.MULL_VERSION}}/${{env.mull-pkg}}
          sudo dpkg -i "$MULL_DEB"

      - *restore_cpm_cache

      - name: Configure cmake for app
        env:
          CC: "/usr/lib/llvm-${{env.MULL_LLVM_MAJOR_VERSION}}/bin/clang"
          CXX: "/usr/lib/llvm-${{env.MULL_LLVM_MAJOR_VERSION}}/bin/clang++"
        working-directory: ${{github.workspace}}/test/application
        run: cmake -Bbuild -DCPM_SOURCE_CACHE=~/cpm-cache -DINFRA_TARGET_NAMESPACE=infra

      - *save_cpm_cache

      - name: Build app and run mull tests
        working-directory: ${{github.workspace}}/test/application
        run: |
          cmake --build build -t infra.mull_tests

  merge_ok:
    runs-on: *runner
    needs: [test, sanitize, mutate]
    if: ${{ !cancelled() }}
    steps:
      - name: Enable merge
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1
